name: Node.js CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install Dependencies and Generate Lock File
        run: |
          npm install
          # This command generates the lock file
          npm ci

      - name: Build and Test
        run: |
          npm run start
          npm test
