# Define the name of your workflow
name: Node.js CI

# Specify when the workflow should be triggered (on push events to the "main" branch)
on:
  push:
    branches:
      - "main"

# Define the jobs for your workflow
jobs:
  # Define the "build" job
  build:
    # Specify the operating system for the job
    runs-on: ubuntu-latest

    # Specify the steps to be executed in the job
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Set up Node.js 18.x environment
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      
      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm install
      
      # Step 4: Run tests
      - name: Run Tests
        run: npm test

  # Define the "deploy" job
  deploy:
    # Specify that this job depends on the successful completion of the "build" job
    needs: build

    # Specify the operating system for the job
    runs-on: ubuntu-latest

    # Specify the steps to be executed in the job
    steps:
      # Step 1: Render Deploy Action
      - name: Render Deploy Action
        # Use the "johnbeynon/render-deploy-action" action
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API }}
